// QB initialization
export const INIT_QB_REQUEST = 'INIT_QB_REQUEST';
export const INIT_QB_REQUEST_SUCCESS = 'INIT_QB_REQUEST_SUCCESS';
export const INIT_QB_REQUEST_FAIL = 'INIT_QB_REQUEST_FAIL';
export const SETUP_TOKEN = 'SETUP_TOKEN';
export const START_SESSION_WITH_TOKEN_SUCCESS = 'START_SESSION_WITH_TOKEN_SUCCESS';
export const START_SESSION_WITH_TOKEN_FAIL = 'START_SESSION_WITH_TOKEN_FAIL';
// User authentication
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_GET_SESSION_REQUEST = 'AUTH_GET_SESSION_REQUEST';
export const AUTH_GET_SESSION_SUCCESS = 'AUTH_GET_SESSION_SUCCESS';
export const AUTH_GET_SESSION_FAIL = 'AUTH_GET_SESSION_FAIL';
export const START_WITH_TOKEN = 'START_WITH_TOKEN';
// QB chat authentication
export const CHAT_IS_CONNECTED_REQUEST = 'CHAT_IS_CONNECTED_REQUEST';
export const CHAT_IS_CONNECTED_SUCCESS = 'CHAT_IS_CONNECTED_SUCCESS';
export const CHAT_IS_CONNECTED_FAIL = 'CHAT_IS_CONNECTED_FAIL';
export const CHAT_CONNECT_REQUEST = 'CHAT_CONNECT_REQUEST';
export const CHAT_CONNECT_SUCCESS = 'CHAT_CONNECT_SUCCESS';
export const CHAT_CONNECT_FAIL = 'CHAT_CONNECT_FAIL';
export const CHAT_CONNECT_AND_SUBSCRIBE = 'CHAT_CONNECT_AND_SUBSCRIBE';
export const CHAT_DISCONNECT_REQUEST = 'CHAT_DISCONNECT_REQUEST';
export const CHAT_DISCONNECT_SUCCESS = 'CHAT_DISCONNECT_SUCCESS';
export const CHAT_DISCONNECT_FAIL = 'CHAT_DISCONNECT_FAIL';
export const CHAT_RECONNECT_SUCCESS = 'CHAT_RECONNECT_SUCCESS';
// QB Users
export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST';
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_CREATE_FAIL = 'USERS_CREATE_FAIL';
export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAIL = 'USERS_UPDATE_FAIL';
export const USERS_GET_REQUEST = 'USERS_GET_REQUEST';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_FAIL = 'USERS_GET_FAIL';
export const USERS_SELECT = 'USERS_SELECT';
export const USERS_BULK_SELECT = 'USERS_BULK_SELECT';
export const USERS_SET_FILTER = 'USERS_SET_FILTER';
export const USERS_SET_PAGE = 'USERS_SET_PAGE';

// QB Info
export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
// Device UDID and registration token for Push notifications
export const DEVICE_UDID_SET = 'DEVICE_UDID_SET';
export const DEVICE_UDID_REMOVE = 'DEVICE_UDID_REMOVE';
export const PUSH_TOKEN_SET = 'PUSH_TOKEN_SET';
export const PUSH_TOKEN_REMOVE = 'PUSH_TOKEN_REMOVE';
export const CREATE_PUSH_SUBSCRIPTIONS = 'CREATE_PUSH_SUBSCRIPTIONS';
export const REMOVE_PUSH_SUBSCRIPTIONS = 'REMOVE_PUSH_SUBSCRIPTIONS';
// Network connection state
export const NETWORK_STATE_CHANGED = 'NETWORK_STATE_CHANGED';
// Notification type
export const NOTIFICATION_TYPE_CREATED = '1';
export const NOTIFICATION_TYPE_ADDED = '2';
export const NOTIFICATION_TYPE_LEAVE = '3';
